CREATE OR REPLACE STREAM "DESTINATION_SQL_STREAM" 
("sensorId" INTEGER, "avg_tempt" INTEGER);

CREATE OR REPLACE PUMP "STREAM_PUMP" 

AS 
INSERT INTO "DESTINATION_SQL_STREAM"

SELECT STREAM 
   "sensorId", 
   AVG("currentTemperature") OVER TEN_SECOND_SLIDING_WINDOW AS "temp_count"

FROM "SOURCE_SQL_STREAM_001"

WINDOW TEN_SECOND_SLIDING_WINDOW AS 
(
  PARTITION BY "sensorId"
  RANGE INTERVAL '10' SECOND PRECEDING);